export const LINKS = {
  cv: '/files/cv-2026-angello-lazar.pdf',
  linkedin: 'https://www.linkedin.com/in/angello-lazar-b60162155/',
  github: 'https://github.com/alo-code',
  twitter: 'https://twitter.com/0x_ALo',
  calendly: 'https://calendly.com/angellolazar/intro',
  suavetech: 'https://suavetech.solutions',
  ibmix: 'https://www.ibm.com/consulting/ibmix',
  dataearn: 'https://dataearn.com',
  zero: 'https://zerodao.com',
  vmex: 'https://vmex.finance',
  pintswap: 'https://pintswap.exchange',
  raeri: 'https://raeri.co/',
  rebarlabs: 'https://rebarlabs.io',
  baton: 'https://www.baton.co',
  augustdigital: 'https://augustdigital.io',
  ups: 'https://www.ups.com',
  smiledirectclub: 'https://smiledirectclub.com',
  agco: 'https://www.agcocorp.com'
};
